Configuration file: /mnt/c/Users/gadia/Dropbox/Websites/blog/_config.yml
[31m  Dependency Error: Yikes! It looks like you don't have /mnt/c/Users/gadia/Dropbox/Websites/blog/_plugins/publish.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- FileUtils' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! [0m
jekyll 3.9.0 | Error:  /mnt/c/Users/gadia/Dropbox/Websites/blog/_plugins/publish.rb
/mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/external.rb:68:in `rescue in block in require_with_graceful_fail': /mnt/c/Users/gadia/Dropbox/Websites/blog/_plugins/publish.rb (Jekyll::Errors::MissingDependencyException)
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/external.rb:56:in `block in require_with_graceful_fail'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/external.rb:55:in `each'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:87:in `block in require_plugin_files'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:85:in `each'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:85:in `require_plugin_files'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/site.rb:114:in `setup'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/site.rb:32:in `initialize'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:30:in `new'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:30:in `process'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/bin/jekyll:25:in `load'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/bin/jekyll:25:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- FileUtils (LoadError)
Did you mean?  fileutils
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/_plugins/publish.rb:1:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/external.rb:55:in `each'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:87:in `block in require_plugin_files'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:85:in `each'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:85:in `require_plugin_files'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/site.rb:114:in `setup'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/site.rb:32:in `initialize'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:30:in `new'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:30:in `process'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/bin/jekyll:25:in `load'
	from /mnt/c/Users/gadia/Dropbox/Websites/blog/new_vendor/bundle/ruby/3.2.0/bin/jekyll:25:in `<main>'
